# Configuration for TDA Hyperparameters
# 3, 2
# --- Positive Cache Configuration ---
positive:
  enabled: False
  shot_capacity: 0
  alpha: 1.0
  beta: 8.0 

# --- Negative Cache Configuration ---
negative:
  enabled: False
  shot_capacity: 0
  alpha: 0.117
  beta: 1.0
  entropy_threshold:
    lower: 0.2
    upper: 0.5 
  mask_threshold:
    lower: 0.03
    upper: 1.0