# Configuration for TDA Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 2.0
  beta: 7.0 

# --- Negative Cache Configuration ---
negative:
  enabled: True
  shot_capacity: 2
  alpha: 0.117
  beta: 1.0
  entropy_threshold:
    lower: 0.2
    upper: 0.5 
  mask_threshold:
    lower: 0.03
    upper: 1.0